import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navber/Navbar";
import Footer from "@/components/footer/Footer";
import { CallProvider } from "@/context/callcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={geistSans.className} >
        <CallProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </CallProvider>
      </body>
    </html>
  );
}


// import { CallProvider } from "@/context/callcontext"; 
// import "./globals.css";

// export const metadata = {
//   title: "KeenKeeper",
//   description: "Manage your friends effectively",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" data-theme="light">
//       <body>
//         <CallProvider>
//           {children}
//         </CallProvider>
//       </body>
//     </html>
//   );
// }